Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace TaskDay2.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;

namespace TaskDay2.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/CourseController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TaskDay2.Controllers;
using TaskDay2.Models;
using TaskDay2.Repository;
using TaskDay2.Repository;
using TaskDay2.ViewModels;

namespace TaskDay2.Controllers
{
    public class CourseController : Controller
    {
        IDepartmentRepository _departmentRepository;
        ICourseRepository _courseRepository;
        
        public CourseController(ICourseRepository courseRepository, IDepartmentRepository departmentRepository)
        {
            _courseRepository = courseRepository;
            _departmentRepository = departmentRepository;
        }

        [AcceptVerbs("GET", "POST")]
        public IActionResult ValidateCrsMinDegree(int CrsMinDegree, int CrsDegree)
        {
            if (CrsMinDegree >= CrsDegree)
            {
                return Json($"Course Minimum Degree must be lower than Course Degree.");
            }

            return Json(true);
        }

        // Index (All Courses Table) + Search
        public IActionResult Index(string searchString)
        {
            var courses = _courseRepository.GetAllCoursesWithDepartment();

            if (!string.IsNullOrEmpty(searchString))
            {
                courses = courses.Where(c => c.CrsName.Contains(searchString)).ToList();
            }

            return View(courses);
        }

        // Details (1 Course only)
        public IActionResult Details(int id)
        {
            Course course = _courseRepository.GetCourseById(id);
            if (course == null)
            {
                return NotFound();
            }
            return View(course);
        }

        // Create Course
        public IActionResult Create()
        {
            ViewBag.DepartmentList = _departmentRepository.GetAllDepartments().Select(d => new SelectListItem
            {
                Value = d.DeptId.ToString(),
                Text = d.DeptName
            });
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Course course)
        {
            if (ModelState.IsValid == true)
            {
                try
                {
                    _courseRepository.AddCourse(course);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("DepId", "Please Select a Department");
                }
                
            }
            ViewBag.DepartmentList = _departmentRepository.GetAllDepartments().Select(d => new SelectListItem
            {
                Value = d.DeptId.ToString(),
                Text = d.DeptName
            });
            return View(course);
        }


        // Edit Course 
        public IActionResult Edit(int id)
        {
            Course course = _courseRepository.GetCourseById(id);
            if (course == null)
            {
                return NotFound();
            }
            ViewBag.DepartmentList = new SelectList(_departmentRepository.GetAllDepartments(), "DeptId", "DeptName");
            return View(course);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, Course course)
        {
            if (id != course.CrsId)
            {
                return NotFound();
            }

            if (ModelState.IsValid == true)
            {
                try
                {
                    _courseRepository.UpdateCourse(course);
                    return RedirectToAction("Index");
                }
                catch (DbUpdateConcurrencyException)
                {
                    ModelState.AddModelError("", "Unable to save changes. The course was deleted by another user.");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "Unable to save changes.");
                }
            }
            ViewBag.DepartmentList = new SelectList(_departmentRepository.GetAllDepartments(), "DeptId", "DeptName");
            return View(course);
        }

        // Delete Course 
        public IActionResult Delete(int id)
        {
            Course course = _courseRepository.GetCourseById(id);
            if (course == null)
            {
                return NotFound();
            }
            return View(course);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            _courseRepository.DeleteCourse(id);
            return RedirectToAction("Index");
        }

        //public class CourseController : Controller
        //{
        //    MyDbContext context = new MyDbContext();

        //    [AcceptVerbs("GET", "POST")]
        //    public IActionResult ValidateCrsMinDegree(int CrsMinDegree, int CrsDegree)
        //    {
        //        if (CrsMinDegree >= CrsDegree)
        //        {
        //            return Json($"Course Minimum Degree must be lower than Course Degree.");
        //        }

        //        return Json(true);
        //    }

        //    // Index (All Courses Table) + Search
        //    public IActionResult Index(string searchString)
        //    {
        //        var courses = context.Course.Include(c => c.Department).ToList();

        //        if (!string.IsNullOrEmpty(searchString))
        //        {
        //            courses = courses.Where(c => c.CrsName.Contains(searchString)).ToList();
        //        }

        //        return View(courses);
        //    }

        //    // Details (1 Course only)
        //    public IActionResult Details(int id)
        //    {
        //        using (var context = new MyDbContext())
        //        {
        //            var course = context.Course.Find(id);
        //            return View(course);
        //        }
        //    }

        //    // Create Course
        //    public IActionResult Create()
        //    {
        //        ViewBag.DepartmentList = new SelectList(context.Department.ToList(), "DeptId", "DeptName");
        //        return View();
        //    }

        //    [HttpPost]
        //    [ValidateAntiForgeryToken]
        //    public IActionResult Create(Course course)
        //    {
        //        if (ModelState.IsValid == true)
        //        {
        //            try {
        //                context.Course.Add(course);
        //                context.SaveChanges();
        //                return RedirectToAction("Index");

        //            }catch (Exception ex)
        //            {
        //                ModelState.AddModelError("DeptId", "Please Select a Department");
        //            }
        //        }
        //        ViewBag.DepartmentList = new SelectList(context.Department.ToList(), "DeptId", "DeptName");
        //        return View(course);
        //    }


        //    // Edit Course 
        //    public IActionResult Edit(int id)
        //    {
        //        var course = context.Course.Find(id);
        //        if (course == null)
        //        {
        //            return NotFound();
        //        }
        //        ViewBag.DepartmentList = new SelectList(context.Department.ToList(), "DeptId", "DeptName");
        //        return View(course);
        //    }

        //    [HttpPost]
        //    [ValidateAntiForgeryToken]
        //    public IActionResult Edit(int id, Course course)
        //    {
        //        if (id != course.CrsId)
        //        {
        //            return NotFound();
        //        }

        //        if (ModelState.IsValid==true)
        //        {
        //            context.Update(course);
        //            context.SaveChanges();
        //            return RedirectToAction("Index");
        //        }
        //        ViewBag.DepartmentList = new SelectList(context.Department.ToList(), "DeptId", "DeptName");
        //        return View(course);
        //    }

        //    // Delete Course 
        //    [HttpPost]
        //    public IActionResult Delete(int id)
        //    {
        //        var course = context.Course.Find(id);
        //        if (course == null)
        //        {
        //            return NotFound();
        //        }
        //        context.Course.Remove(course);
        //        context.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //}

    }
}

Controllers/DepartmentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using TaskDay2.Models;
using TaskDay2.Repository;
using TaskDay2.ViewModels;

namespace TaskDay2.Controllers
{
    public class DepartmentController : Controller
    {
        IDepartmentRepository _departmentRepository;

        public DepartmentController(IDepartmentRepository departmentRepository)
        {
            _departmentRepository = departmentRepository;
        }

        // Index (All Departments Table) + Search
        public IActionResult Index(string searchString)
        {
            var departments = _departmentRepository.GetAllDepartments();

            if (!string.IsNullOrEmpty(searchString))
            {
                departments = departments.Where(d => d.DeptName.Contains(searchString)).ToList();
            }

            return View(departments);
        }

        // Details (1 Department only)
        public IActionResult Details(int id)
        {
            Department department = _departmentRepository.GetDepartmentById(id);
            if (department == null)
            {
                return NotFound();
            }
            return View(department);
        }

        // Create Department
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Department department)
        {
            if (ModelState.IsValid)
            {
                _departmentRepository.AddDepartment(department);
                return RedirectToAction("Index");
            }
            return View(department);
        }


        // Edit Department 
        public IActionResult Edit(int id)
        {
            Department department = _departmentRepository.GetDepartmentById(id);
            if (department == null)
            {
                return NotFound();
            }
            return View(department);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, Department department)
        {
            if (id != department.DeptId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _departmentRepository.UpdateDepartment(department);
                    return RedirectToAction("Index");
                }
                catch (DbUpdateConcurrencyException)
                {
                    ModelState.AddModelError("", "Unable to save changes. The department was deleted by another user.");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "Unable to save changes.");
                }
            }
            return View(department);
        }

        // Delete Department 
        public IActionResult Delete(int id)
        {
            Department department = _departmentRepository.GetDepartmentById(id);
            if (department == null)
            {
                return NotFound();
            }
            return View(department);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            _departmentRepository.DeleteDepartment(id);
            return RedirectToAction("Index");
        }


        ////////////////////////////////////////////    Need to be edited     //////////////////////////////////////
        //  GetCoursesByDepartment --> when I Add or Edit instructor, the Course choosen depends on the Department I choosed
        public IActionResult GetCoursesByDepartment(int deptId)
        {
            MyDbContext context = new MyDbContext();
            var courses = context.Course.Where(c => c.DeptId == deptId)
                                           .Select(c => new SelectListItem
                                           {
                                               Value = c.CrsId.ToString(),
                                               Text = c.CrsName
                                           })
                                           .ToList();

            return Json(courses);
        }
    }
}

Views/Shared/_AdvLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title></title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
@*    <link href="/img/favicon.ico" rel="icon">
*@    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Nunito:wght@600;700;800&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="/lib/animate/animate.min.css" rel="stylesheet">
    <link href="/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="/css/bootstrap.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="/css/style.css" rel="stylesheet">
</head>

<body>
    <!-- Spinner Start -->
    <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
        <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
            <span class="sr-only">Loading...</span>
        </div>
    </div>
    <!-- Spinner End -->
    <!-- Navbar Start -->

    <!-------------------- Partial View (Using HTML Helper) -------------------->

    @await Html.PartialAsync("_NavPartial")

    <!-- Navbar End -->

    <div class="container">
        <div class="row">
        </div>
    </div>
    @RenderBody()


    <!-- Footer Start -->
    <div class="container-fluid bg-dark text-light footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">
        <div class="container py-5">
            <div class="row g-5">
                <div class="col-lg-3 col-md-6">
                    <h4 class="text-white mb-3">Quick Link</h4>
                    <a class="btn btn-link" href="">About Us</a>
                    <a class="btn btn-link" href="">Contact Us</a>
                    <a class="btn btn-link" href="">Privacy Policy</a>
                    <a class="btn btn-link" href="">Terms & Condition</a>
                    <a class="btn btn-link" href="">FAQs & Help</a>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h4 class="text-white mb-3">Contact</h4>
                    <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>354 Geish Road, Alexandria, Egypt</p>
                    <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+20 155 0550555</p>
                    <p class="mb-2"><i class="fa fa-envelope me-3"></i>learnspot@gmail.com</p>
                    <div class="d-flex pt-2">
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-youtube"></i></a>
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-linkedin-in"></i></a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h4 class="text-white mb-3">Gallery</h4>
                    <div class="row g-2 pt-2">
                        <div class="col-4">
                            <img class="img-fluid bg-light p-1" src="/img/course-1.jpg" alt="">
                        </div>
                        <div class="col-4">
                            <img class="img-fluid bg-light p-1" src="/img/course-2.jpg" alt="">
                        </div>
                        <div class="col-4">
                            <img class="img-fluid bg-light p-1" src="/img/course-3.jpg" alt="">
                        </div>
                        <div class="col-4">
                            <img class="img-fluid bg-light p-1" src="/img/course-2.jpg" alt="">
                        </div>
                        <div class="col-4">
                            <img class="img-fluid bg-light p-1" src="/img/course-3.jpg" alt="">
                        </div>
                        <div class="col-4">
                            <img class="img-fluid bg-light p-1" src="/img/course-1.jpg" alt="">
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h4 class="text-white mb-3">Newsletter</h4>
                    <p>Stay Up-to-Date with Our Latest News and Updates.</p>
                    <div class="position-relative mx-auto" style="max-width: 400px;">
                        <input class="form-control border-0 w-100 py-3 ps-4 pe-5" type="text" placeholder="Your email">
                        <button type="button" class="btn btn-primary py-2 position-absolute top-0 end-0 mt-2 me-2">SignUp</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="copyright">
                <div class="row">
                    <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                        © <a href="#"> 2023 LearnSpot</a>, &nbsp; All Right Reserved.
                    </div>
                    <div class="col-md-6 text-center text-md-end">
                        <div class="footer-menu">
                            <a href="">Home</a>
                            <a href="">Cookies</a>
                            <a href="">Help</a>
                            <a href="">FQAs</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer End -->
    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="fa-solid fa-arrow-up"></i></a>


    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="/lib/wow/wow.min.js"></script>
    <script src="/lib/easing/easing.min.js"></script>
    <script src="/lib/waypoints/waypoints.min.js"></script>
    <script src="/lib/owlcarousel/owl.carousel.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/js/all.min.js"></script>

    <!-- Template Javascript -->
    <script src="/js/main.js"></script>
    @RenderSection("Scripts",false)

</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TaskDay2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TaskDay2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>



        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Institute</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Instructor" asp-action="Index">Instructors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Course" asp-action="Index">Courses</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>



    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Institute - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_MyLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>

    <div style="background-color:pink; height:20%;">
        <h1>Header (common)</h1>
    </div>

    <div style="background-color:yellowgreen;">
        @RenderBody()
    </div>
    
    <div style="background-color:pink; height:10%;">
        <h1>Footer (common)</h1>

    </div>

</body>
</html>

Views/Shared/_NavPartial.cshtml
<nav class="navbar navbar-expand-lg bg-white navbar-light shadow sticky-top p-0">
    <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand d-flex align-items-center px-4 px-lg-5">
        <h2 class="m-0 text-primary"><i class="fa fa-book me-3"></i>LearnSpot</h2>
    </a>
    <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <div class="navbar-nav ms-auto p-4 p-lg-0">
            <a asp-area="" asp-controller="Home" asp-action="Index" class="nav-item nav-link">Home</a>
            <a asp-area="" asp-controller="About" asp-action="Index" class="nav-item nav-link">About</a>
            <a asp-area="" asp-controller="Department" asp-action="Index" class="nav-item nav-link">Departments</a>
            <a asp-area="" asp-controller="Course" asp-action="Index" class="nav-item nav-link">Courses</a>
            <a asp-area="" asp-controller="Instructor" asp-action="Index" class="nav-item nav-link">Instructors</a>
            <a asp-area="" asp-controller="Contact" asp-action="Index" class="nav-item nav-link">Contact</a>
        </div>
        <a href="" class="btn btn-primary py-4 px-lg-5 d-none d-lg-block">Join Now<i class="fa fa-arrow-right ms-3"></i></a>
    </div>
</nav>