Models/Course.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TaskDay2.Models
{
    public class Course
    {
        [Key]
        public int CrsId { get; set; }

        [Display(Name = "Course Name")]
        [MaxLength(25, ErrorMessage = "Course Name must be with a maximum legnth of 25 Characters")]
        [MinLength(2, ErrorMessage = "Course Name must be with a minimum Legnth of 2 Characters")]
        [UniqueCrsNamePerDept]
        public string CrsName { get; set; }

        [Display(Name = "Course Degree")]
        [Range(50,100, ErrorMessage = "Course Degree Must be between 50 and 100")]
        public int CrsDegree { get; set; }

        [Display(Name = "Course Minimum Degree")]
        [Required]
        [Remote("ValidateCrsMinDegree", "Course", AdditionalFields = "CrsDegree")]
        public int CrsMinDegree { get; set; }


        [ForeignKey("Department")]
        [Display(Name = "Department")]
        public int DeptId { get; set; }

        public bool IsDeleted { get; set; } = false;

        public virtual Department? Department { get; set; }
        public virtual List<Instructor> Instructors { get; set; } = new List<Instructor>();
        public virtual List<CrsResult>? CrsResults { get; set; } = new List<CrsResult>();
    }
}

Controllers/CourseController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TaskDay2.Controllers;
using TaskDay2.Models;
using TaskDay2.Repository;
using TaskDay2.Repository;
using TaskDay2.ViewModels;

namespace TaskDay2.Controllers
{
    public class CourseController : Controller
    {
        IDepartmentRepository _departmentRepository;
        ICourseRepository _courseRepository;
        
        public CourseController(ICourseRepository courseRepository, IDepartmentRepository departmentRepository)
        {
            _courseRepository = courseRepository;
            _departmentRepository = departmentRepository;
        }

        [AcceptVerbs("GET", "POST")]
        public IActionResult ValidateCrsMinDegree(int CrsMinDegree, int CrsDegree)
        {
            if (CrsMinDegree >= CrsDegree)
            {
                return Json($"Course Minimum Degree must be lower than Course Degree.");
            }

            return Json(true);
        }

        // Index (All Courses Table) + Search
        public IActionResult Index(string searchString)
        {
            var courses = _courseRepository.GetAllCoursesWithDepartment();

            if (!string.IsNullOrEmpty(searchString))
            {
                courses = courses.Where(c => c.CrsName.Contains(searchString)).ToList();
            }

            return View(courses);
        }

        // Details (1 Course only)
        public IActionResult Details(int id)
        {
            Course course = _courseRepository.GetCourseById(id);
            if (course == null)
            {
                return NotFound();
            }
            return View(course);
        }

        // Create Course
        public IActionResult Create()
        {
            ViewBag.DepartmentList = _departmentRepository.GetAllDepartments().Select(d => new SelectListItem
            {
                Value = d.DeptId.ToString(),
                Text = d.DeptName
            });
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Course course)
        {
            if (ModelState.IsValid == true)
            {
                try
                {
                    _courseRepository.AddCourse(course);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("DepId", "Please Select a Department");
                }
                
            }
            ViewBag.DepartmentList = _departmentRepository.GetAllDepartments().Select(d => new SelectListItem
            {
                Value = d.DeptId.ToString(),
                Text = d.DeptName
            });
            return View(course);
        }


        // Edit Course 
        public IActionResult Edit(int id)
        {
            Course course = _courseRepository.GetCourseById(id);
            if (course == null)
            {
                return NotFound();
            }
            ViewBag.DepartmentList = new SelectList(_departmentRepository.GetAllDepartments(), "DeptId", "DeptName");
            return View(course);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, Course course)
        {
            if (id != course.CrsId)
            {
                return NotFound();
            }

            if (ModelState.IsValid == true)
            {
                try
                {
                    _courseRepository.UpdateCourse(course);
                    return RedirectToAction("Index");
                }
                catch (DbUpdateConcurrencyException)
                {
                    ModelState.AddModelError("", "Unable to save changes. The course was deleted by another user.");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "Unable to save changes.");
                }
            }
            ViewBag.DepartmentList = new SelectList(_departmentRepository.GetAllDepartments(), "DeptId", "DeptName");
            return View(course);
        }

        // Delete Course 
        public IActionResult Delete(int id)
        {
            Course course = _courseRepository.GetCourseById(id);
            if (course == null)
            {
                return NotFound();
            }
            return View(course);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            _courseRepository.DeleteCourse(id);
            return RedirectToAction("Index");
        }

        //public class CourseController : Controller
        //{
        //    MyDbContext context = new MyDbContext();

        //    [AcceptVerbs("GET", "POST")]
        //    public IActionResult ValidateCrsMinDegree(int CrsMinDegree, int CrsDegree)
        //    {
        //        if (CrsMinDegree >= CrsDegree)
        //        {
        //            return Json($"Course Minimum Degree must be lower than Course Degree.");
        //        }

        //        return Json(true);
        //    }

        //    // Index (All Courses Table) + Search
        //    public IActionResult Index(string searchString)
        //    {
        //        var courses = context.Course.Include(c => c.Department).ToList();

        //        if (!string.IsNullOrEmpty(searchString))
        //        {
        //            courses = courses.Where(c => c.CrsName.Contains(searchString)).ToList();
        //        }

        //        return View(courses);
        //    }

        //    // Details (1 Course only)
        //    public IActionResult Details(int id)
        //    {
        //        using (var context = new MyDbContext())
        //        {
        //            var course = context.Course.Find(id);
        //            return View(course);
        //        }
        //    }

        //    // Create Course
        //    public IActionResult Create()
        //    {
        //        ViewBag.DepartmentList = new SelectList(context.Department.ToList(), "DeptId", "DeptName");
        //        return View();
        //    }

        //    [HttpPost]
        //    [ValidateAntiForgeryToken]
        //    public IActionResult Create(Course course)
        //    {
        //        if (ModelState.IsValid == true)
        //        {
        //            try {
        //                context.Course.Add(course);
        //                context.SaveChanges();
        //                return RedirectToAction("Index");

        //            }catch (Exception ex)
        //            {
        //                ModelState.AddModelError("DeptId", "Please Select a Department");
        //            }
        //        }
        //        ViewBag.DepartmentList = new SelectList(context.Department.ToList(), "DeptId", "DeptName");
        //        return View(course);
        //    }


        //    // Edit Course 
        //    public IActionResult Edit(int id)
        //    {
        //        var course = context.Course.Find(id);
        //        if (course == null)
        //        {
        //            return NotFound();
        //        }
        //        ViewBag.DepartmentList = new SelectList(context.Department.ToList(), "DeptId", "DeptName");
        //        return View(course);
        //    }

        //    [HttpPost]
        //    [ValidateAntiForgeryToken]
        //    public IActionResult Edit(int id, Course course)
        //    {
        //        if (id != course.CrsId)
        //        {
        //            return NotFound();
        //        }

        //        if (ModelState.IsValid==true)
        //        {
        //            context.Update(course);
        //            context.SaveChanges();
        //            return RedirectToAction("Index");
        //        }
        //        ViewBag.DepartmentList = new SelectList(context.Department.ToList(), "DeptId", "DeptName");
        //        return View(course);
        //    }

        //    // Delete Course 
        //    [HttpPost]
        //    public IActionResult Delete(int id)
        //    {
        //        var course = context.Course.Find(id);
        //        if (course == null)
        //        {
        //            return NotFound();
        //        }
        //        context.Course.Remove(course);
        //        context.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //}

    }
}

Controllers/TraineeController.cs
using System.Linq;
using System.Security.Cryptography;
using Microsoft.AspNetCore.Cors.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TaskDay2.Models;
using TaskDay2.ViewModels;


namespace TaskDay2.Controllers
{
    public class TraineeController : Controller
    {

        private readonly MyDbContext db;

        public TraineeController()
        {
            db = new MyDbContext();
        }

        public IActionResult ShowResult(int tid, int cid)
        {

            TraineeCourseResultViewModel td = new TraineeCourseResultViewModel();

            var trainee = db.CrsResult.Where(c => c.CrsId == cid && c.TraId == tid)
                .Include(c => c.Course)
                .Include(t => t.Trainee).FirstOrDefault();

            td.TraineeName = trainee.Trainee.TraName;
            td.CourseName = trainee.Course.CrsName;
            td.CourseDegree = trainee.CrsResultDegree;

            td.Color = td.CourseDegree > trainee.Course.CrsMinDegree ? "green" : "red";
            return View(td);
            //    /Trainee/ShowResult?tid=1&cid=1
        }



        public IActionResult ShowTraineeResult(int tid)
        {
            var courseList = db.CrsResult.Where(c => c.TraId == tid)
                .Include(c => c.Course)
                .Include(t => t.Trainee).ToList();

            if (courseList == null)
            {
                return NotFound();
            }
            List<TraineeCourseResultViewModel> td = new List<TraineeCourseResultViewModel>();

            for (int i = 0; i < courseList.Count; i++)
            {

                var course = new TraineeCourseResultViewModel();


                course.TraineeName = courseList[i].Trainee.TraName;
                course.CourseName = courseList[i].Course.CrsName;
                course.CourseDegree = courseList[i].CrsResultDegree;
                course.Color = course.CourseDegree > courseList[i].Course.CrsMinDegree ? "green" : "red";

                td.Add(course);
            }

            return View(td);
        }
        public IActionResult ShowCourseResult(int cid)
        {
            var traineeList = db.CrsResult.Where(c => c.CrsId == cid)
                .Include(c => c.Course)
                .Include(t => t.Trainee).ToList();

            if (traineeList == null)
            {
                return NotFound();
            }
            List<TraineeCourseResultViewModel> td = new List<TraineeCourseResultViewModel>();

            for (int i = 0; i < traineeList.Count; i++)
            {

                var course = new TraineeCourseResultViewModel();


                course.TraineeName = traineeList[i].Trainee.TraName;
                course.CourseName = traineeList[i].Course.CrsName;
                course.CourseDegree = traineeList[i].CrsResultDegree;
                course.Color = course.CourseDegree > traineeList[i].Course.CrsMinDegree ? "green" : "red";

                td.Add(course);
            }

            return View(td);
        }
    }
}

Views/Course/Create.cshtml
@model Course
@{
    ViewData["Title"] = "Add Course";
}

<div class="container">
    <div class="row">
        <h1 class="my-4">Add Course</h1>

        <form asp-action="Create" method="post" enctype="multipart/form-data">
            @Html.ValidationSummary(false, "", new { @class = "text-danger" })
            <div class="form-group my-2">
                <label asp-for="CrsName">Course Name</label>
                <input asp-for="CrsName" class="form-control" />
                @Html.ValidationMessageFor( Course => Course.CrsName, "",new {@class= "text-danger"})
            </div>
            <div class="form-group my-2">
                <label asp-for="CrsDegree">Course Degree</label>
                <input asp-for="CrsDegree" class="form-control" />
                @Html.ValidationMessageFor( Course => Course.CrsDegree, "",new {@class= "text-danger"})
            </div>
            <div class="form-group my-2">
                <label asp-for="CrsMinDegree">Course Min. Degree</label>
                <input asp-for="CrsMinDegree" class="form-control" />
                @Html.ValidationMessageFor( Course => Course.CrsMinDegree, "",new {@class= "text-danger"})
            </div>
            <div class="form-group my-2">
                <label asp-for="DeptId">Department</label>
                <select asp-for="DeptId" asp-items="ViewBag.DepartmentList" class="form-control">
                    <option value="0">--Select Department--</option>
                </select>
                @Html.ValidationMessageFor( Course => Course.DeptId, "",new {@class= "text-danger"})
            </div>
            <button type="submit" class="btn btn-primary">Add Course</button>
        </form>
    </div>
</div>


<!----------Client Side Validation---------->
@section Scripts{
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

Views/Course/Edit.cshtml
@model Course
@{
    ViewData["Title"] = "Edit Course";
}

<div class="container">
    <div class="row">

        <h1 class="my-4">Edit Course</h1>

        <form asp-action="Edit" asp-route-id="@Model.CrsId" method="post" enctype="multipart/form-data">
            @Html.AntiForgeryToken()
            <input type="hidden" asp-for="CrsId" />
            <div class="form-group my-2">
                <label asp-for="CrsName">Course Name</label>
                <input asp-for="CrsName" class="form-control" />
            </div>
            <div class="form-group my-2">
                <label asp-for="CrsDegree">Course Degree</label>
                <input asp-for="CrsDegree" class="form-control" />
            </div>
            <div class="form-group my-2">
                <label asp-for="CrsMinDegree">Course Min. Degree</label>
                <input asp-for="CrsMinDegree" class="form-control" />
            </div>
            <div class="form-group my-2">
                <label asp-for="DeptId">Department</label>
                <select asp-for="DeptId" asp-items="ViewBag.DepartmentList" class="form-control">
                    <option value="0">--Select Department--</option>
                </select>
            </div>
            <button type="submit" class="btn btn-primary">Edit Course</button>
        </form>

    </div>
</div>

Views/Course/Index.cshtml
@model List<Course>

@{
    ViewData["Title"] = "Index";
    int i = 1;
}

<div class="container">
    <div class="row">

        <h1 class="my-4">Courses</h1>

        <form asp-action="Index" method="get">
            <div class="input-group mb-3">
                <input type="text" class="form-control" placeholder="Search by name" name="searchString" />
                <div class="input-group-append ms-3">
                    <button class="btn btn-outline-secondary" type="submit">Search</button>
                </div>
            </div>
        </form>


        <a class="btn btn-primary my-3 col-2" asp-action="Create">Add Course</a>

        <table class="table table-bordered table-hover text-center">
            <tr>
                <th>No.</th>
                <th>Course Name</th>
                <th>Course Max Degree</th>
                <th>Course Min Degree</th>
                <th>Department</th>
                <th>Results</th>
                <th>Edit</th>
                <th>Delete</th>

            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@(i++)</td>
                    <td>@item.CrsName</td>
                    <td>@item.CrsDegree</td>
                    <td>@item.CrsMinDegree</td>
                    <td>@(item.Department?.DeptName)</td>
                    <td><a class="btn btn-outline-secondary" asp-controller="Trainee" asp-action="ShowCourseResult" asp-route-cid="@item.CrsId">Course Results</a></td>
                    <td><a class="btn btn-outline-success" asp-action="Edit" asp-route-id="@item.CrsId">Edit Course</a></td>
                    <td>
                        <form asp-action="Delete" method="post" onsubmit="return confirm('Are you sure you want to delete this course?');">
                            <input type="hidden" name="id" value="@item.CrsId" />
                            <button type="submit" class="btn btn-outline-danger">Delete Course</button>
                        </form>
                    </td>
                </tr>
            }
        </table>

    </div>
</div>